// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.3
// source: sketch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KLLSketch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*OrderedRow          `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	N             int32                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KLLSketch) Reset() {
	*x = KLLSketch{}
	mi := &file_sketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KLLSketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KLLSketch) ProtoMessage() {}

func (x *KLLSketch) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KLLSketch.ProtoReflect.Descriptor instead.
func (*KLLSketch) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{0}
}

func (x *KLLSketch) GetRows() []*OrderedRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *KLLSketch) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type OrderedRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*OrderedValue        `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderedRow) Reset() {
	*x = OrderedRow{}
	mi := &file_sketch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderedRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderedRow) ProtoMessage() {}

func (x *OrderedRow) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderedRow.ProtoReflect.Descriptor instead.
func (*OrderedRow) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{1}
}

func (x *OrderedRow) GetValues() []*OrderedValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type OrderedValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*OrderedValue_IntVal
	//	*OrderedValue_FloatVal
	Value         isOrderedValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderedValue) Reset() {
	*x = OrderedValue{}
	mi := &file_sketch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderedValue) ProtoMessage() {}

func (x *OrderedValue) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderedValue.ProtoReflect.Descriptor instead.
func (*OrderedValue) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{2}
}

func (x *OrderedValue) GetValue() isOrderedValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OrderedValue) GetIntVal() int32 {
	if x != nil {
		if x, ok := x.Value.(*OrderedValue_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *OrderedValue) GetFloatVal() float32 {
	if x != nil {
		if x, ok := x.Value.(*OrderedValue_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

type isOrderedValue_Value interface {
	isOrderedValue_Value()
}

type OrderedValue_IntVal struct {
	IntVal int32 `protobuf:"varint,1,opt,name=int_val,json=intVal,proto3,oneof"`
}

type OrderedValue_FloatVal struct {
	FloatVal float32 `protobuf:"fixed32,2,opt,name=float_val,json=floatVal,proto3,oneof"`
}

func (*OrderedValue_IntVal) isOrderedValue_Value() {}

func (*OrderedValue_FloatVal) isOrderedValue_Value() {}

type ReverseQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phi           int32                  `protobuf:"varint,1,opt,name=phi,proto3" json:"phi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseQuery) Reset() {
	*x = ReverseQuery{}
	mi := &file_sketch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseQuery) ProtoMessage() {}

func (x *ReverseQuery) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseQuery.ProtoReflect.Descriptor instead.
func (*ReverseQuery) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseQuery) GetPhi() int32 {
	if x != nil {
		return x.Phi
	}
	return 0
}

type QueryReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phi           int32                  `protobuf:"varint,1,opt,name=phi,proto3" json:"phi,omitempty"`
	N             int32                  `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReturn) Reset() {
	*x = QueryReturn{}
	mi := &file_sketch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReturn) ProtoMessage() {}

func (x *QueryReturn) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReturn.ProtoReflect.Descriptor instead.
func (*QueryReturn) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{4}
}

func (x *QueryReturn) GetPhi() int32 {
	if x != nil {
		return x.Phi
	}
	return 0
}

func (x *QueryReturn) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type MergeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeReply) Reset() {
	*x = MergeReply{}
	mi := &file_sketch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeReply) ProtoMessage() {}

func (x *MergeReply) ProtoReflect() protoreflect.Message {
	mi := &file_sketch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeReply.ProtoReflect.Descriptor instead.
func (*MergeReply) Descriptor() ([]byte, []int) {
	return file_sketch_proto_rawDescGZIP(), []int{5}
}

func (x *MergeReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_sketch_proto protoreflect.FileDescriptor

var file_sketch_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x09, 0x4b, 0x4c, 0x4c, 0x53, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64,
	0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e, 0x22, 0x39, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x65, 0x64, 0x52, 0x6f, 0x77, 0x12, 0x2b, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x51, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1d, 0x0a,
	0x09, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x00, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x0c, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x68, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x70, 0x68, 0x69, 0x22, 0x2d, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x68, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x68, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x4e, 0x22, 0x24, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xb3, 0x01, 0x0a,
	0x08, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x08, 0x4d, 0x65, 0x72,
	0x67, 0x65, 0x4b, 0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x4c,
	0x4c, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x08,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4b, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0f, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4b, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x72, 0x75, 0x68, 0x6e, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x64, 0x2d, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sketch_proto_rawDescOnce sync.Once
	file_sketch_proto_rawDescData []byte
)

func file_sketch_proto_rawDescGZIP() []byte {
	file_sketch_proto_rawDescOnce.Do(func() {
		file_sketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sketch_proto_rawDesc), len(file_sketch_proto_rawDesc)))
	})
	return file_sketch_proto_rawDescData
}

var file_sketch_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sketch_proto_goTypes = []any{
	(*KLLSketch)(nil),    // 0: proto.KLLSketch
	(*OrderedRow)(nil),   // 1: proto.OrderedRow
	(*OrderedValue)(nil), // 2: proto.OrderedValue
	(*ReverseQuery)(nil), // 3: proto.ReverseQuery
	(*QueryReturn)(nil),  // 4: proto.QueryReturn
	(*MergeReply)(nil),   // 5: proto.MergeReply
}
var file_sketch_proto_depIdxs = []int32{
	1, // 0: proto.KLLSketch.rows:type_name -> proto.OrderedRow
	2, // 1: proto.OrderedRow.values:type_name -> proto.OrderedValue
	0, // 2: proto.Sketcher.MergeKll:input_type -> proto.KLLSketch
	2, // 3: proto.Sketcher.QueryKll:input_type -> proto.OrderedValue
	3, // 4: proto.Sketcher.ReverseQueryKll:input_type -> proto.ReverseQuery
	5, // 5: proto.Sketcher.MergeKll:output_type -> proto.MergeReply
	4, // 6: proto.Sketcher.QueryKll:output_type -> proto.QueryReturn
	2, // 7: proto.Sketcher.ReverseQueryKll:output_type -> proto.OrderedValue
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sketch_proto_init() }
func file_sketch_proto_init() {
	if File_sketch_proto != nil {
		return
	}
	file_sketch_proto_msgTypes[2].OneofWrappers = []any{
		(*OrderedValue_IntVal)(nil),
		(*OrderedValue_FloatVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sketch_proto_rawDesc), len(file_sketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sketch_proto_goTypes,
		DependencyIndexes: file_sketch_proto_depIdxs,
		MessageInfos:      file_sketch_proto_msgTypes,
	}.Build()
	File_sketch_proto = out.File
	file_sketch_proto_goTypes = nil
	file_sketch_proto_depIdxs = nil
}
